### ISSUE TITLE
Enhance User Experience and Clarity with Expanded Documentation

### ISSUE THREAD

**Issue by ALIPHATICHYD** [JairTorres1003/JT-View-Exports-SVG#105]
Hello there! I'm ALIPHATIC, an enthusiastic user and supporter of the "View Exports SVG" extension. Its functionality and ease of use have pleased me, and I believe that adding more documentation might improve the user experience and clarify crucial capabilities.

I propose that the following parts be added:

Features: A full overview of the extension's capabilities, including specific benefits for various phases of the developer workflow (e.g., icon selection, integration with other frameworks, and so on).
Troubleshooting: A guide to typical problems and solutions, with images or GIFs for visual aid.
Settings: An explanation of the extension's configurable preferences and their implications on its behaviour.
Frequently Asked Questions: Answers to frequently asked questions concerning installation, compatibility, and usage.

**Comment by JairTorres1003** [comment]
Hello @ALIPHATICHYD

Thank you for your support and for suggesting improvements to the "View Exports SVG" extension! I appreciate your enthusiasm, and I completely agree that more comprehensive documentation can enhance the user experience.

I am diligently working on these updates and hope that you will soon enjoy more comprehensive and helpful documentation. I appreciate your patience and ongoing support for the extension.

Greetings!

**Comment by ALIPHATICHYD** [comment]
Its really nice hearing from you 
So will I be assigned to it or you are working on it from your end.

**Comment by JairTorres1003** [comment]
Hello @ALIPHATICHYD!

The complete documentation for the "View Exports SVG" extension is now available on the [GitHub repository's wiki](https://github.com/JairTorres1003/JT-View-Exports-SVG/wiki). You can check it out there for detailed information about the extension's functionality and features.

Thank you for your interest, and I hope you find the documentation helpful!

Greetings!

**Comment by ALIPHATICHYD** [comment]
I will take note of that 
Thank you very much

**Comment by JairTorres1003** [comment]
---
You're welcome! If you have any further questions in the future or encounter new uncertainties, feel free to reopen this issue or [create a new one](https://github.com/JairTorres1003/JT-View-Exports-SVG/issues) in the repository. I'll be more than happy to assist you. Good luck with your project!
