### ISSUE TITLE
Support globs for asset path

### ISSUE THREAD

**Issue by Akkuma** [JairTorres1003/JT-View-Exports-SVG#128]
**Is your feature request related to a problem? Please describe.**
It would be really beneficial if the asset path could be configured as a glob. Currently, new files need to keep being added manually, which isn't great and it causes PRs show these getting added.

**Describe the solution you'd like**
Support for glob paths such as `'/packages/**/icons/*.tsx`

**Describe alternatives you've considered**
There are none

**Additional context**

**Comment by JairTorres1003** [comment]
Hi, @Akkuma 

Thank you for your suggestion. This feature request is related to the functionality discussed in [#129](https://github.com/JairTorres1003/JT-View-Exports-SVG/issues/129). The feature to support glob paths for asset configuration is already being considered and planned for implementation.

As this functionality addresses the concerns raised in this issue, I am closing this issue. Please refer to [#129](https://github.com/JairTorres1003/JT-View-Exports-SVG/issues/129) for updates and progress on this feature.

Thank you for your understanding and for contributing to the project.
